from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class SourceMapping:
    file_name: str
    source_code: str
    dataset: str
    source_price_unit: str
    price_multiplier_to_irr: int | None
    source_id_column: str | None
    title_column: str | None
    brand_column: str | None
    category_column: str | None
    merchant_column: str | None
    price_column: str | None
    old_price_column: str | None
    discount_column: str | None
    cash_back_column: str | None
    availability_column: str | None
    product_url_column: str | None
    image_url_column: str | None
    search_keyword_column: str | None
    availability_true_values: frozenset[str]
    availability_false_values: frozenset[str]
    notes: str = ""


TRUE_VALUES = frozenset({"true", "1", "yes", "in stock", "instock", "available"})
FALSE_VALUES = frozenset({"false", "0", "no", "out of stock", "outofstock", "unavailable"})
NO_AVAILABILITY_VALUES = frozenset()


MAPPINGS_BY_FILE: dict[str, SourceMapping] = {
    "arkaapi_first_50_pages.xlsx": SourceMapping(
        file_name="arkaapi_first_50_pages.xlsx",
        source_code="arka",
        dataset="all_categories_first_50_pages",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column="id",
        title_column="title",
        brand_column="brand",
        category_column="category",
        merchant_column=None,
        price_column="sale_price",
        old_price_column="regular_price",
        discount_column=None,
        cash_back_column=None,
        availability_column="availability",
        product_url_column="link",
        image_url_column="picture",
        search_keyword_column=None,
        availability_true_values=NO_AVAILABILITY_VALUES,
        availability_false_values=NO_AVAILABILITY_VALUES,
        notes=(
            "Availability values are invalid for stock normalization; preserve the raw value "
            "but set is_available to NULL for every Arka record."
        ),
    ),
    "Digikala - Health & Beauty.xlsx": SourceMapping(
        file_name="Digikala - Health & Beauty.xlsx",
        source_code="digikala",
        dataset="health_beauty",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column=None,
        title_column="Product Title",
        brand_column=None,
        category_column=None,
        merchant_column=None,
        price_column="Product Price",
        old_price_column=None,
        discount_column=None,
        cash_back_column=None,
        availability_column=None,
        product_url_column=None,
        image_url_column=None,
        search_keyword_column=None,
        availability_true_values=NO_AVAILABILITY_VALUES,
        availability_false_values=NO_AVAILABILITY_VALUES,
        notes="The source column named URL contains category labels, not HTTP product URLs.",
    ),
    "Digikala - Home & Electronics - 2026-08-03.xlsx": SourceMapping(
        file_name="Digikala - Home & Electronics - 2026-08-03.xlsx",
        source_code="digikala",
        dataset="home_electronics",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column=None,
        title_column="Product Title",
        brand_column=None,
        category_column=None,
        merchant_column=None,
        price_column="Product Price",
        old_price_column=None,
        discount_column=None,
        cash_back_column=None,
        availability_column=None,
        product_url_column=None,
        image_url_column=None,
        search_keyword_column=None,
        availability_true_values=NO_AVAILABILITY_VALUES,
        availability_false_values=NO_AVAILABILITY_VALUES,
        notes="The source column named URL contains category labels, not HTTP product URLs.",
    ),
    "Khanoumi Data.xlsx": SourceMapping(
        file_name="Khanoumi Data.xlsx",
        source_code="khanoumi",
        dataset="all_categories",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column="page_unique",
        title_column="title",
        brand_column=None,
        category_column="category_name",
        merchant_column="seller_name",
        price_column="current_price",
        old_price_column="old_price",
        discount_column=None,
        cash_back_column=None,
        availability_column="availability",
        product_url_column="page_url",
        image_url_column="image_link",
        search_keyword_column=None,
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
    ),
    "SnappPay - All Cats - 2026-08-23.csv": SourceMapping(
        file_name="SnappPay - All Cats - 2026-08-23.csv",
        source_code="snapp_pay",
        dataset="all_categories",
        source_price_unit="IRR",
        price_multiplier_to_irr=1,
        source_id_column="product_id",
        title_column="product_name",
        brand_column=None,
        category_column="type",
        merchant_column="merchant_name",
        price_column="price",
        old_price_column="old_price",
        discount_column="discount",
        cash_back_column="cash_back",
        availability_column="available",
        product_url_column="referral_link",
        image_url_column="image_link",
        search_keyword_column="keyword",
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
    ),
    "SnappPay - Digital Accessories - 2026-08-23.xlsx": SourceMapping(
        file_name="SnappPay - Digital Accessories - 2026-08-23.xlsx",
        source_code="snapp_pay",
        dataset="digital_accessories",
        source_price_unit="IRR",
        price_multiplier_to_irr=1,
        source_id_column="product_id",
        title_column="product_name",
        brand_column=None,
        category_column="type",
        merchant_column="merchant_name",
        price_column="price",
        old_price_column="old_price",
        discount_column="discount",
        cash_back_column="cash_back",
        availability_column="available",
        product_url_column="referral_link",
        image_url_column="image_link",
        search_keyword_column="keyword",
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
        notes="The filename has an .xlsx extension, but the actual content is CSV.",
    ),
    "SnappPay - Health & Beauty - 2026-08-23.xlsx": SourceMapping(
        file_name="SnappPay - Health & Beauty - 2026-08-23.xlsx",
        source_code="snapp_pay",
        dataset="health_beauty",
        source_price_unit="IRR",
        price_multiplier_to_irr=1,
        source_id_column="product_id",
        title_column="product_name",
        brand_column=None,
        category_column="type",
        merchant_column="merchant_name",
        price_column="price",
        old_price_column="old_price",
        discount_column="discount",
        cash_back_column="cash_back",
        availability_column="available",
        product_url_column="referral_link",
        image_url_column="image_link",
        search_keyword_column="keyword",
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
    ),
    "SnappPay - Mobile.xlsx": SourceMapping(
        file_name="SnappPay - Mobile.xlsx",
        source_code="snapp_pay",
        dataset="mobile",
        source_price_unit="IRR",
        price_multiplier_to_irr=1,
        source_id_column="product_id",
        title_column="product_name",
        brand_column=None,
        category_column="type",
        merchant_column="merchant_name",
        price_column="price",
        old_price_column="old_price",
        discount_column="discount",
        cash_back_column="cash_back",
        availability_column="available",
        product_url_column="referral_link",
        image_url_column="image_link",
        search_keyword_column="keyword",
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
    ),
    "sormehshop_products.xlsx": SourceMapping(
        file_name="sormehshop_products.xlsx",
        source_code="sormehshop",
        dataset="all_products",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column="id",
        title_column="title",
        brand_column="brand",
        category_column="category",
        merchant_column=None,
        price_column="sale_price",
        old_price_column="regular_price",
        discount_column=None,
        cash_back_column=None,
        availability_column="availability",
        product_url_column="link",
        image_url_column="image_link",
        search_keyword_column=None,
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
    ),
    "technolife_snapp_products_first_40_pages.xlsx": SourceMapping(
        file_name="technolife_snapp_products_first_40_pages.xlsx",
        source_code="technolife",
        dataset="snapp_products_first_40_pages",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column="id",
        title_column="title",
        brand_column="brand",
        category_column="category",
        merchant_column=None,
        price_column="sale_price",
        old_price_column="regular_price",
        discount_column=None,
        cash_back_column=None,
        availability_column="availability",
        product_url_column="link",
        image_url_column="image_link",
        search_keyword_column=None,
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
    ),
    "Torob - Home & Electronics - 2026-08-22.xlsx": SourceMapping(
        file_name="Torob - Home & Electronics - 2026-08-22.xlsx",
        source_code="torob",
        dataset="home_electronics",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column=None,
        title_column="Product Title",
        brand_column=None,
        category_column=None,
        merchant_column=None,
        price_column="Product Price",
        old_price_column=None,
        discount_column=None,
        cash_back_column=None,
        availability_column=None,
        product_url_column=None,
        image_url_column=None,
        search_keyword_column="Search Query",
        availability_true_values=NO_AVAILABILITY_VALUES,
        availability_false_values=NO_AVAILABILITY_VALUES,
    ),
    "Torob Products - 17 June - Merged Files.csv": SourceMapping(
        file_name="Torob Products - 17 June - Merged Files.csv",
        source_code="torob",
        dataset="merged_products",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column=None,
        title_column="Product Title",
        brand_column=None,
        category_column=None,
        merchant_column=None,
        price_column="Product Price",
        old_price_column=None,
        discount_column=None,
        cash_back_column=None,
        availability_column=None,
        product_url_column=None,
        image_url_column=None,
        search_keyword_column=None,
        availability_true_values=NO_AVAILABILITY_VALUES,
        availability_false_values=NO_AVAILABILITY_VALUES,
        notes="Shop URL identifies the shop rather than an individual product and is not loaded as product_url.",
    ),
    "TorobPay - Health & Beauty - 2026-08-23.xlsx": SourceMapping(
        file_name="TorobPay - Health & Beauty - 2026-08-23.xlsx",
        source_code="torob_pay",
        dataset="health_beauty",
        source_price_unit="UNKNOWN",
        price_multiplier_to_irr=None,
        source_id_column=None,
        title_column="Product Title",
        brand_column=None,
        category_column=None,
        merchant_column=None,
        price_column="Product Price",
        old_price_column=None,
        discount_column=None,
        cash_back_column=None,
        availability_column=None,
        product_url_column=None,
        image_url_column=None,
        search_keyword_column="Search Query",
        availability_true_values=NO_AVAILABILITY_VALUES,
        availability_false_values=NO_AVAILABILITY_VALUES,
        notes="All observed Product Price values are NULL; retain records in staging with a missing-price warning.",
    ),
    "xiaomixiaomi_products.xlsx": SourceMapping(
        file_name="xiaomixiaomi_products.xlsx",
        source_code="xiaomixiaomi",
        dataset="all_products",
        source_price_unit="IRT",
        price_multiplier_to_irr=10,
        source_id_column="id",
        title_column="title",
        brand_column="description.برند",
        category_column="category",
        merchant_column=None,
        price_column="sale_price",
        old_price_column="regular_price",
        discount_column=None,
        cash_back_column=None,
        availability_column="availability",
        product_url_column="link",
        image_url_column="image_link",
        search_keyword_column=None,
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
    ),
    "zanoone_products - 2026-08-23.csv": SourceMapping(
        file_name="zanoone_products - 2026-08-23.csv",
        source_code="zanoone",
        dataset="all_products",
        source_price_unit="IRR",
        price_multiplier_to_irr=1,
        source_id_column="id",
        title_column="title",
        brand_column="brand",
        category_column="category",
        merchant_column=None,
        price_column="sale_price",
        old_price_column="regular_price",
        discount_column=None,
        cash_back_column=None,
        availability_column="availability",
        product_url_column="link",
        image_url_column="image_link",
        search_keyword_column=None,
        availability_true_values=TRUE_VALUES,
        availability_false_values=FALSE_VALUES,
    ),
}


def get_mapping(file_path: Path) -> SourceMapping:
    try:
        return MAPPINGS_BY_FILE[file_path.name]
    except KeyError as error:
        raise KeyError(f"No source mapping exists for file: {file_path.name}") from error


def mapped_source_codes() -> set[str]:
    return {mapping.source_code for mapping in MAPPINGS_BY_FILE.values()}